$kind: http-request
name: GET api/settings
url: "{{baseUrl}}/api/settings"
method: GET
headers:
  Content-Type: application/json
  Accept: application/json
auth:
  type: noauth
examples: ./.resources/GET api-settings.resources/examples
order: 171000
